blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/bootstrap-email/bootstrap-email/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
  - name: Help
    url: https://github.com/bootstrap-email/bootstrap-email/discussions/new?category=help
    about: 'If you have a question or need help, ask a question on the discussion forums.'
  - name: Documentation Issue
    url: https://github.com/bootstrap-email/documentation-0.x
    about: 'For documentation issues, suggest changes on our documentation repository.'
  - name: Kind Words
    url: https://github.com/bootstrap-email/bootstrap-email/discussions/new?category=kind-words
    about: "Have something nice to say about Bootstrap Email? We'd love to hear it!"
